import { Metadata } from "next"
import { ErrorWrapper } from "./error-wrapper"

export const metadata:Metadata = {
  title: {
    default: "Next.js Tutorial - ProCodeJs",
    template: "%s | ProCodeJs",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{background: "lightblue", padding: "1rem"}}>

          <p>Header</p>
        </header>
        <ErrorWrapper>
        {children}
        </ErrorWrapper>
        <footer style={{background: "lightgreen", padding: "1rem"}}>

          <p>Footer</p>
        </footer>
        </body>
    </html>
  )
}
